/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test
    public void testRestaurantToString() {
        Restaurant restaurant = new Restaurant("yazan", "$$");
        assertEquals("Name: yazan, Stars: no rate, Price : $$", restaurant.toString());

    }

    @Test
    public void testAddTOTheater() {
        Theater theater = new Theater("ja3fer");
        theater.addMovie("HunterX Hunter");
        theater.addMovie("Hunter");
        assertEquals("Theater: ja3fer, Movies: [HunterX Hunter, Hunter]\n", theater.toString());
    }
    @Test
    public void testShopToString() {
        Shop shop = new Shop("MK","very good","$$$");

        assertEquals("Shop: MK, Description: very good, Price: $$$\n", shop.toString());
    }
    @Test
    public void testRemoveMovie() {
        Theater theater = new Theater("ja3fer");
        theater.addMovie("HunterX Hunter");
        theater.addMovie("Hunter");
        theater.removeMovie("Hunter");
        assertEquals("Theater: ja3fer, Movies: [HunterX Hunter]\n", theater.toString());
    }

    @Test
    public void testReview (){

        Review review =new Review("yazan","yazan",5);
        assertEquals("yazan,  Rating: 5, Author: yazan", review.toString());
    }
}


