/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        System.out.println("hello");
        Restaurant restaurant=new Restaurant("yazan","$$");
        Review review =new Review("yazan","yazan",5);
        System.out.println(review);
        restaurant.addReview(review);
        System.out.println(restaurant);
        System.out.println("============================================================");
        Theater theater = new Theater("ja3fer");
        theater.addMovie("HunterX Hunter");
        theater.addMovie("Hunter");
        System.out.println(theater);
        System.out.println("============================================================");
        theater.addReview(review);
        theater.removeMovie("Hunter");
        System.out.println(theater);
        System.out.println("============================================================");
        Shop shop = new Shop("MK","very good","$$$");
        shop.addReview(review);
        System.out.println(shop);


    }
}
